### PR TITLE
Changes to make the CMS Xcache into production

### PR DESCRIPTION
**Pull request by efajardo**

### CODE REVIEW

**Comment by efajardo** [comment]
@igor-sfiligoi when you have time can you review this PR

**Comment by sfiligoi** [comment]
Can you please convert the yaml to apps/v1 deployment?
The v1beta1 is deprecated, and Dima may have already removed the support altogether.

Note that the syntax is a bit changed.
You can see 
https://github.com/sfiligoi/prp-osg-pool/blob/master/k8s/osg-wn-cpu-suncave-4.yaml
for an example.

Also, all pods require the explicit declaration of CPU and memory usage. Please add both requests and limits.

**Comment by efajardo** [comment]
@igor-sfiligoi I made the changes you requested

**Comment by efajardo** [comment]
Can we merge this now @sfiligoi

**Pull request merged**
